groups:
- name: cpu-node
  rules:
  - record: job_instance_mode:process_cpu_seconds_total:avg_rate5m
    expr: avg by (job, instance, mode) (rate(process_cpu_seconds_total[5m]))

- name: DHCPAlerts
  rules:
  - alert: RogueDHCPServerDetected
    # replace with your known DHCP servers
    expr: dhcp_offer_per_server_count > 0 and ignoring(server_ip) dhcp_offer_per_server_count unless (dhcp_offer_per_server_count{server_ip=~"^(192\\.168\\.0\\.254)$"})
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Rogue DHCP Server Detected"
      description: "A rogue DHCP server with IP {{ $labels.server_ip }} is detected on the network."

- name: NodeAlerts
  rules:
  - alert: RamOver90
    expr: ((1 - (node_memory_MemAvailable_bytes{instance="localhost:9100", job="node_exporter"} / node_memory_MemTotal_bytes{instance="localhost:9100", job="node_exporter"})) * 100) > 90
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "RAM consumption over 90%"
      description: "RAM consumption over 90% threshold"
