{
 "title": "DNS + DHCP monitoring",
 "description": "Display data scraped from Prometheus and dnsmasq_exporter.\n\nUses this exporter https://github.com/google/dnsmasq_exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(dnsmasq_cachesize,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(dnsmasq_cachesize{job=\"$job\"},instance)"
    }
   },
   {
    "name": "dhcp_message_type",
    "query": {
     "query": "label_values(dhcp_message_total,message_type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "DHCP Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DHCP Server count in network",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dhcp_message_total{message_type=\"ACK\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "DHCP Time Series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "dhcp_message_total",
   "type": "timeseries",
   "description": "Rate of total messages for the specified message_type.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by(source_mac) (idelta(dhcp_message_total{message_type=\"$dhcp_message_type\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "dhcp_request_total",
   "type": "timeseries",
   "description": "Client accepts DHCP server offer and requests to be assigned to that address.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
   "targets": [
    { "expr": "idelta(dhcp_request_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "dhcp_ack_total",
   "type": "timeseries",
   "description": "DHCP server accepts client request to commit to DHCP configuration.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
   "targets": [
    { "expr": "idelta(dhcp_ack_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "dhcp_discover_total",
   "type": "timeseries",
   "description": "Client requests for DHCP configuration.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "idelta(dhcp_discover_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "dhcp_offer_total",
   "type": "timeseries",
   "description": "DHCP server offered DHCP configuration for client.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "targets": [
    { "expr": "idelta(dhcp_offer_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "dhcp_nak_total",
   "type": "timeseries",
   "description": "DHCP server does not accept client request for DHCP configuration.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "targets": [
    { "expr": "idelta(dhcp_nak_total[1m])", "legendFormat": "__auto" }
   ]
  },
  { "title": "DNS Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CacheSize",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnsmasq_cachesize{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Leases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnsmasq_leases{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dnsmasq_auth{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ScrapeTime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_threads{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "DNS Time series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "dnsmasq_insertions",
   "type": "timeseries",
   "description": "DNS cache insertions",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "increase(dnsmasq_insertions{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "dnsmasq_evictions",
   "type": "timeseries",
   "description": "DNS cache evictions: numbers of entries which replaced an unexpired cache entry",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "increase(dnsmasq_evictions{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "dnsmasq_misses",
   "type": "timeseries",
   "description": "DNS cache misses: queries which had to be forwarded",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "increase(dnsmasq_misses{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "dnsmasq_hits",
   "type": "timeseries",
   "description": "DNS queries answered locally (cache hits)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "increase(dnsmasq_hits{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "dnsmasq_servers_queries",
   "type": "timeseries",
   "description": "DNS queries on upstream server",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "expr": "increase(dnsmasq_servers_queries{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "dnsmasq_servers_queries_failed",
   "type": "timeseries",
   "description": "DNS queries failed on upstream server",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "targets": [
    {
     "expr": "increase(dnsmasq_servers_queries_failed{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}